server {
    listen 80;
    listen [::]:80;
    server_name localhost;

    # En-têtes de sécurité critiques (Anti-XSS, Anti-Clickjacking, Sniffing)
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;

    # Fichiers de logs de l'infrastructure
    access_log /var/log/nginx/livguinar_access.log;
    error_log /var/log/nginx/livguinar_error.log;

    # 1. Gestion du trafic web et API classique (HTTP)
    location / {
        proxy_pass http://app:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 2. Configuration SRT : Tunnel de Géolocalisation Temps Réel (WebSockets)
    location /socket.io {
        proxy_pass http://app:5000/socket.io;
        proxy_http_version 1.1;
        
        # En-têtes réseaux requis pour maintenir le tunnel persistant ouvert
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Bloquer l'accès direct aux fichiers cachés (.env, .git, etc.)
    location ~ /\. {
        deny all;
    }
}